### ISSUE TITLE
[MacOS] Pod install error saying a package requires higher minimum deployment target (but the app is already set)

### ISSUE THREAD

**Issue by yasinarik** [nativeshell/nativeshell#120]
## Hi @knopp! 
First of all, I want to thank you for developing all of this. This is a huge achievement to be honest.

## Problem
I am getting an error after `cargo run` command. It complains that I have to use an **_higher minimum deployment target_** bu I already set that.

### What Have I Done?:

- I am using a `MacBook Pro (intel cpu)`, and the current `MacOS version is: 10.15.5`
- I have successfully installed Rust, and run **NativeShell Example** from the repo. I tried every feature and it worked flawlessly.
- I have copied `.cargo, resources, src, build.rs, Cargo.toml,` from **App Template** repo to my existing Flutter project folder.
- The project is set to `10.15` on XCode application. 
- Also I make sure that it is `MACOSX_DEPLOYMENT_TARGET = 10.15` by manually checking this file at: `macos/Flutter/ephemeral/.symlinks/plugins/flutter_web_auth/example/macos/Runner.xcodeproj/project.pbxproj`
- I added the package `nativeshell: ^0.1.10` into `pubspec.yaml`
- By the way, I should say that I am using `FVM (Flutter Version Manager)`. So I also refreshed the packages by `fvm flutter pub get`
- I installed the pods by doing `cd macos` --> `pod install`
- I have added a `launch.json` file in `.vscode` folder in order to use that `Flutter: Attach to Process` process.
- Finally I ran `cargo run` and it generated lots of files into `./target` folder. Then it gave this error below.

### Error Log:
```
** Build failed with error **

  External Tool Failed!
  Status: ExitStatus(ExitStatus(256))
  Command: "pod" "install"
  Stderr:

  Stdout:
  Analyzing dependencies
  [!] CocoaPods could not find compatible versions for pod "flutter_web_auth":
    In Podfile:
      flutter_web_auth (from `/PATH_TO_APP/target/debug/build/app_template-c9e9887c415ba219/out/xcode/symlinks/flutter_web_auth/macos`)

  Specs satisfying the `flutter_web_auth (from `/PATH_TO_APP/target/debug/build/app_template-c9e9887c415ba219/out/xcode/symlinks/flutter_web_auth/macos`)` dependency were found, but they required a higher minimum deployment target.


  --- stderr
  thread 'main' panicked at 'explicit panic', build.rs:29:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by knopp** [comment]
Can you try setting `MACOSX_DEPLOYMENT_TARGET` as environment variable before running `cargo run`?

**Comment by yasinarik** [comment]
> Can you try setting `MACOSX_DEPLOYMENT_TARGET` as environment variable before running `cargo run`?

Surely, where can I find it? I just couldn't see. Thanks for replying this quick!

**Comment by knopp** [comment]
I mean just do

`MACOSX_DEPLOYMENT_TARGET=10.15 cargo run`

**Comment by knopp** [comment]
Btw. nativeshell flutter build is completely separate from "regular" flutter build. It doesn't do any of the files inside `macos` folder. The deployment target during build is taken from environment variable `MACOSX_DEPLOYMENT_TARGET` and it should be passed to the xcode build that builds pods.

**Comment by yasinarik** [comment]
> I mean just do
> 
> `MACOSX_DEPLOYMENT_TARGET=10.15 cargo run`

After running it like this, it worked 🚀! Thanks a lot. Is there a way to make it permanent? Like storing that env variable? Because I think I have checked every possible place I find written `MACOSX_DEPLOYMENT_TARGET` yet it didn't work until a did your suggestion.

----
> Btw. nativeshell flutter build is completely separate from "regular" flutter build.
Actually, I learnt that by reading other issues, etc. but I just wanted to test it anyways.

**Comment by knopp** [comment]
I think you can should be able to call `std::env::set_var("MACOSX_DEPLOYMENT_TARGET", "10.15")` in `build.rs` before calling `build_flutter()`.

**Comment by yasinarik** [comment]
> I think you should be able to call `std::env::set_var("MACOSX_DEPLOYMENT_TARGET", "10.15")` in `build.rs` before calling `build_flutter()`.

Yes, that also worked. Thanks a lot for spending your time! Just for a future reference, for any other reader, I am adding the code block below:
**Changes made in this file:** `build.rs`

```rust
fn main() {
    std::env::set_var("MACOSX_DEPLOYMENT_TARGET", "10.15");  // ---> HERE GOES THE ENV
    if let Err(error) = build_flutter() {
        println!("\n** Build failed with error **\n\n{}", error);
        panic!();
    }
}
```
