### ISSUE TITLE
[Question] Changing the default Flutter entry point from 'lib/main.dart' to something like 'lib/main_with_nativeshell.dart'

### ISSUE THREAD

**Issue by yasinarik** [nativeshell/nativeshell#121]
Hello again dear @knopp,

After a little exploration, I thought it would be better for me to have 2 different Dart/Flutter entry points because I would still want to build/run (either in debug or release mode) a desktop application by default Flutter, and also with Rust Nativeshell. 

Moreover, I want to be able to do that quickly. 

So basically, if I want to run it without Nativeshell, I will just run `flutter run` command or use the debug button on VSCode. If I want the Nativeshell support, I will run `cargo run` command and the 2nd entry point will be used for the build.

**How can I change that config?** The answer could be pretty simple but I just wanted to write these down in case another reader wonders. Here is how I do that:

### [Option 1] The standart entry point `flutter run`
**main.dart:**

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Some other unrelated stuff here...

  runApp(App()); // Runs the app directly. The default behavior.
}
```

### [Option 2] The entry point that I want `cargo run` command to build upon:
**main_with_nativeshell.dart:**

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Some other unrelated stuff here...

  runApp(NativeShellWrapper()); // Runs a wrapper that wraps the App. 
}
```

### This is just a basic helper/wrapper class that brings the Nativeshell support:
**nativeshell_wrapper.dart:**
```dart
import 'package:flutter/material.dart';
import 'package:nativeshell/nativeshell.dart';
import 'package:APP_NAME/screens/00_app/app.dart';

class NativeShellWrapper extends StatefulWidget {
  const NativeShellWrapper({Key? key}) : super(key: key);

  @override
  _NativeShellWrapperState createState() => _NativeShellWrapperState();
}

class _NativeShellWrapperState extends State<NativeShellWrapper> {
  @override
  Widget build(BuildContext context) {
    /// Widgets from Nativeshell package...
    return WindowWidget(
      onCreateState: (initData) {
        WindowState? state;
        state ??= MainWindowState();
        return state;
      },
    );
  }
}


/* -------------------------------------------------------------------------- */
/*                               MainWindowState                              */
/* -------------------------------------------------------------------------- */
class MainWindowState extends WindowState {
  @override
  WindowSizingMode get windowSizingMode => WindowSizingMode.atLeastIntrinsicSize;

  @override
  Widget build(BuildContext context) {
    return WindowLayoutProbe(
      child: ConstrainedBox(
        constraints: BoxConstraints(
          minHeight: 800,
          minWidth: 1200,
        ),
        child: App(),
      ),
    );
  }
}
```
-----
Maybe you had already written on this topic but I couldn't manage to find. I am sorry if that is the case but I wanted to ask this question. Thanks a lot,

Best,
Yasin

**Comment by knopp** [comment]
You can override `target_file` inside `FlutterOptions` struct that gets passed into `Flutter::build` to specify custom entry point (i.e. `lib/main_with_nativeshell.dart`).

**Comment by yasinarik** [comment]
> You can override `target_file` inside `FlutterOptions` struct that gets passed into `Flutter::build` to specify custom entry point (i.e. `lib/main_with_nativeshell.dart`).

Thanks for pointing! I managed it thanks to your help and a bit of searching because the lack of my Rust skills ☺️

If anyone wonders, here is what you should do:

1. Changes made in `build.rs` file. 
2. Import the Path by typing this line `use std::path::Path;` (Put it on top of everything like you are importing a Flutter package.)
3. Finally add the relative path of the entry point for Flutter. Here is an example, change it accordingly:
```rust
    Flutter::build(FlutterOptions {
        target_file: Path::new("lib/main_with_nativeshell.dart"),  // *****---> Here is the path override
        ..Default::default()
    })?;
```
4. Done! Now whenever I run `cargo run` command, it builds using the correct Flutter main file which is `main_with_nativeshell.dart` 🚀

**Comment by yasinarik** [comment]
> You can override `target_file` inside `FlutterOptions` struct that gets passed into `Flutter::build` to specify custom entry point (i.e. `lib/main_with_nativeshell.dart`).

Thanks for pointing! I managed it thanks to your help and a bit of searching because the lack of my Rust skills ☺️

If anyone wonders, here is what you should do:

1. Changes made in `build.rs` file. 
2. Import the Path by typing this line `use std::path::Path;` (Put it on top of everything like you are importing a Flutter package.)
3. Finally add the relative path of the entry point for Flutter. Here is an example, change it accordingly:
```rust
    Flutter::build(FlutterOptions {
        target_file: Path::new("lib/main_with_nativeshell.dart"),  // *****---> Here is the path override
        ..Default::default()
    })?;
```
4. Done! Now whenever I run `cargo run` command, it builds using the correct Flutter main file which is `main_with_nativeshell.dart` 🚀
