### ISSUE TITLE
I see 'MinimizeWindow' exists, but unsure of the best way to call it?

### ISSUE THREAD

**Issue by MostHated** [nativeshell/nativeshell#144]
Hey there,
    I have been learning to use the library and have figured out a good few things so far, but am having an issue trying to figure out the best way to call `MinimizeWindow`. 

I am using the libadwaita package and was trying to implement some window controls.

![](https://camo.githubusercontent.com/323cdc16322af66fda54722f629aa5f79154bfe2831996cdaca2b13975d65d30/68747470733a2f2f692e696d6775722e636f6d2f34356850334d522e706e67)

I had setup the following seen below, and window.close() works just fine, and I thought perhaps window.hide() would be minimize, but it seems that it is much more literal than I expected, as when I call that the window disappears completely from the screen as well as the taskbar. I should have expected as much from the name, but at the same time, I don't see any sort of minimize or maximize that could be called in a manner similar to close(). Perhaps I am just looking in the wrong place? I see that it exists in menu items, do I need to somehow call that a specific way?

```dart
  Future<void> windowAction(String action) async {
    switch (action) {
      case 'minimize': await window.hide(); break;
      case 'maximize': await window.activate(); break;
      case 'quit': await window.close(); break;
      default:
    }
  }
```

Any assistance would be greatly appreciated!
Thanks,
-MH

**Comment by knopp** [comment]
There is currently no way to maximize/minimize/restore window in native shell. What you're looking at are probably WindowStateFlags, which inform you about current window state. This is currently a priority, it should be added very soon.
