### ISSUE TITLE
Any way to use this without Dart?

### ISSUE THREAD

**Issue by iMplode-nZ** [nativeshell/nativeshell#15]
I would really like to be able to build a Rust application with Flutter UI without writing code in Dart. Is this at all possible? (I'm willing to have to install dart and stuff, but I don't want to write the ui code in it)

**Comment by knopp** [comment]
That's not possible.

**Comment by iMplode-nZ** [comment]
Would it ever be possible in the future?

**Comment by knopp** [comment]
Rust is used for low level platform specific code. In applications built with NativeShell rust code can be called through platform channels or FFI. But it can not be used to build user interfaces. For that you need to look elsewhere.

FWIW, for building user interfaces dart is, despite lacking some of rust features, probably much more productive language. Especially when you take hot reload into account.

**Comment by iMplode-nZ** [comment]
Well yes, but I don't want to do FFI between a rust game and a dart UI. Rust could work decently well for UI if there were any libraries for it imo.
