### ISSUE TITLE
Higher-level Plugin api akin to flutter-rs

### ISSUE THREAD

**Issue by maxjoehnk** [nativeshell/nativeshell#16]
I'm working on an application written in rust with flutter as the UI and was using [flutter-rs](https://github.com/flutter-rs/flutter-rs/) until now.
I've implemented some custom channels and flutter-rs has a nice abstraction for flutter plugins as well as the different channel types.

Do you have any intentions to implement something similar?

**Comment by knopp** [comment]
Have you taken look at the examples? There are rust channel handlers registered with message manager.

https://github.com/nativeshell/examples/blob/main/src/platform_channels.rs
https://github.com/nativeshell/examples/blob/main/src/file_open_dialog.rs

If you want to you can package your handler as a crate, all you'd need as an entry point is for your plugin to register with message manager.

**Comment by maxjoehnk** [comment]
Yeah I've seen the examples. But if you compare the api to the flutter-rs api it's way more cumbersome to work with.
In flutter-rs all you need to do is implement the trait `MethodCallHandler` and then you can register it with the engine.
There is also a `Plugin` trait which allows registration of channels to the engine.

For reference [here](https://github.com/maxjoehnk/node-based-mizer/blob/main/ui/src/plugin/mod.rs) you can find the usage of the `Plugin` trait and [here](https://github.com/maxjoehnk/node-based-mizer/blob/main/ui/src/plugin/channels/nodes.rs) you can see how the usage of the `MethodCallHandler` trait looks like.

**Comment by knopp** [comment]
I see. Would something like this work? 

https://gist.github.com/knopp/139f7b2b02ce4f59e2649bc1560276c3

The `Plugin` struct is fairly easy to implement on top of existing machinery, but I don't mind including it if it makes things more convenient.

**Comment by knopp** [comment]
So it could be something like this

https://github.com/nativeshell/nativeshell/blob/nativeshell_plugin/nativeshell/src/shell/plugin.rs

and this is how it would be used:

https://github.com/nativeshell/examples/blob/nativeshell_plugin/src/file_open_dialog.rs
https://github.com/nativeshell/examples/blob/nativeshell_plugin/src/platform_channels.rs
https://github.com/nativeshell/examples/blob/nativeshell_plugin/src/main.rs
