### ISSUE TITLE
Fails to build on apple silicon with Flutter 3.0.0

### ISSUE THREAD

**Issue by 0xchase** [nativeshell/nativeshell#164]
Hello,

When building with the new Apple Silicon support, I get the error 

```
Flutter artifact location path at "/Users/chasekanipe/Software/flutter/bin/cache/artifacts/engine/darwin-arm64-release" does not exist! Try running 'flutter precache'
```

The culprit appears to be the line below. It should use the x64 directory as it now contains universal binaries. 

https://github.com/nativeshell/nativeshell/blob/60c6e3db98c318d07975dab4e77131c3bb30d1ab/nativeshell_build/src/artifacts_emitter.rs#L225

**Comment by abnerh69** [comment]
Hi, I solved it by copying folders as:

**darwin-x64** to **darwin-arm64**
**darwin-x64-profile** to **darwin-arm64-profile**
**darwin-x64-release** to **darwin-arm64-release**

finally you will have (as shown on image):

<img width="236" alt="Screen Shot 2022-05-18 at 11 56 29 AM" src="https://user-images.githubusercontent.com/6172846/169099463-5ad68a42-e9cc-4d14-b11e-b25eb8a898eb.png">
