### ISSUE TITLE
Webview Support on Desktop

### ISSUE THREAD

**Issue by ikey4u** [nativeshell/nativeshell#19]
I am writing a dictionary software[wikit](https://github.com/ikey4u/wikit) ,it will render word meaning in html format. But for now, flutter seems having no support for webview on desktop. My question is that will nativeshell support embeded webview?

**Comment by knopp** [comment]
I can image support for and managing a webview window on top of nativeshell app. As for actually embedding webview in flutter hierarchy, that would belong to flutter embedder. There is work on this being done on macOS, but I'm not even sure if it is possible to do on Windows.

**Comment by ikey4u** [comment]
> I can image support for and managing a webview window on top of nativeshell app. As for actually embedding webview in flutter hierarchy, that would belong to flutter embedder. There is work on this being done on macOS, but I'm not even sure if it is possible to do on Windows.

This sounds a little frustrating.

**Comment by putraxor** [comment]
can you give me a reference on "There is work on this being done on macOS", please?

**Comment by knopp** [comment]
https://github.com/flutter/flutter/issues/81320
