### ISSUE TITLE
Examples segfault on linux

### ISSUE THREAD

**Issue by maxjoehnk** [nativeshell/nativeshell#21]
The following actions in the examples app trigger a segfault on Linux:

* moving/resizing windows
* clicking on menu bar item
* opening the menu

I think when the application looses focus it breaks as well but I'm not totally certain.
Right now I've only tested it on my Desktop running Arch with stable Rust 1.53.0 and Flutter 2.2.2.

**Comment by knopp** [comment]
Nativeshell needs flutter master (it's written in the readme). It's going to take a while until flutter stable catches up.

**Comment by knopp** [comment]
If you upgrade flutter to master don't forget to do `flutter pub get` first. After that touch any dart file and try rerunning it. Also there are some window sizing issues on linux currently, should be fixed in main, but the fix is not yet published on pub.

**Comment by maxjoehnk** [comment]
Damn, I've noticed that but did not expect it to matter here.
Maybe this also fixes the release build issue I have in another project with cargo workspaces.

Thanks for the quick response.

**Comment by knopp** [comment]
Just yesterday I landed a fix that for a bug causing OpenGL context corruption on linux when opening new windows, so yeah, it's going to be master for a while :)
