### ISSUE TITLE
Hot Reload

### ISSUE THREAD

**Issue by maxjoehnk** [nativeshell/nativeshell#32]
Have you thought about adding hot reload capabilities?
This would probably require moving parts of the build process into the runtime but would align the developer experience with the standard flutter process.
Obviously this would only work for the dart code and not the rust parts.

**Comment by knopp** [comment]
Hot reload works of course :)

Can you attach to running process (there are vscode launch configuration that do that automatically), after which you can hot reload the code.

**Comment by maxjoehnk** [comment]
Ah nice, than I‘ll have to figure out how to do this with IntelliJ as there doesn’t seem to be an easy way to attach to an external flutter process.
Is this also possible from the web ui? I didn’t notice it in the dart observatory and the flutter devtools don’t seem to be available. At least I haven’t found any references to it.

**Comment by knopp** [comment]
If you just want hot reload you can do it through command line. i.e.

`flutter attach -v -d macos  --debug-url=http://127.0.0.1:62935/tHQyjy6Zdeo\=/ --target=lib/main.dart`

Debug URL is the printed observatory URL. I'm not sure how to access dev tools, I usually just launch it through the DartCode plugin. Also the documentation mentions [attaching in intellij](https://flutter.dev/docs/development/add-to-app/debugging) though I don't know if that works as expected.

**Comment by maxjoehnk** [comment]
Well I guess I should've RTFM.
That will definitely help me, as I only really need the hot reloading.
As far as I can tell the attaching via IntelliJ doesn't work because it requires knowledge of the "device" it's running on but I'll have to check that.
I will note it here if I can get it to work.

Thanks for the quick response!

**Comment by knopp** [comment]
I think the link I've sent mentions selecting the device before arraching. But it is possible that the intellij plugin doesn't recognize NativeShell project and won't let you select the desktop device.
