### ISSUE TITLE
Support for Event channels

### ISSUE THREAD

**Issue by maxjoehnk** [nativeshell/nativeshell#44]
Right now there is support for Method Channels but not for [Event Channels](https://api.flutter.dev/flutter/services/EventChannel-class.html).
I've looked a little bit into it but I'm unsure how it would fit into the existing architecture.

I feel like streams would be a perfect fit but this would require an async executor.

**Comment by knopp** [comment]
The low-ish level api for this would be `shell.MessageManager`, `register_message_handler` and `get_message_sender`. Those operate on messages instead of method calls. I played a bit with async executor that invokes futures on main loop but in the end decided it might not be worth it.

**Comment by knopp** [comment]
This [PR](https://github.com/nativeshell/nativeshell/pull/51/files) adds event channel support.

There are no examples yet, but the usage should be roughtly like this:

```rust
const CHANNEL_APP_NOTIFICATIONS: &str = "channel_name";

pub struct AppState {
    sinks: HashMap<i64, EventSink>,
}

impl AppState {
    pub fn new(context: Context) -> RegisteredEventChannel<Self> {
        Self {
            sinks: HashMap::new(),
        }
        .register(context, CHANNEL_APP_NOTIFICATIONS)
    }

    fn send_message(&self, message: &Value) {
        for sink in self.sinks.values() {
            sink.send_message(message).ok();
        }
    }
}

impl EventChannelHandler for AppState {
    fn register_event_sink(
        &mut self,
        sink: nativeshell::shell::EventSink,
        _listen_argument: Value,
    ) {
        self.sinks.insert(sink.id(), sink);
    }

    fn unregister_event_sink(&mut self, sink_id: i64) {
        self.sinks.remove(&sink_id);
    }
}
```

Dart side:
```dart
   const _appNotificationsChannel = EventChannel('channel_name');
   ...
    _appNotificationsChannel
        .receiveBroadcastStream()
        .listen((event) {...});
```

**Comment by maxjoehnk** [comment]
It's working like a charm. Thank you!
If you want I can add an example using an Async Executor to send stream events down an EventSink.

**Comment by knopp** [comment]
That'd be great! Examples will need some work right now to build with current master. I plan to do that over this weekend (as well as new nativeshell release).
