### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by floatingrain** [nativeshell/nativeshell#54]
I'm using Ubuntu, run `cargo run` then appears:

> warning: `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.48"` did not exit successfully: exit code: 1
> 
> error: failed to run custom build command for `glib-sys v0.14.0`
> 
> Caused by:
>   process didn't exit successfully: `/home/floatingrain/project/examples/target/debug/build/glib-sys-96150614ea46d8b2/build-script-build` (exit code: 1)
>   --- stdout
>   cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=GLIB_2.0_STATIC
>   cargo:rerun-if-env-changed=GLIB_2.0_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:warning=`"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.48"` did not exit successfully: exit code: 1
>   --- stderr
>   Package glib-2.0 was not found in the pkg-config search path.
>   Perhaps you should add the directory containing `glib-2.0.pc'
>   to the PKG_CONFIG_PATH environment variable
>   No package 'glib-2.0' found
>   Package glib-2.0 was not found in the pkg-config search path.
>   Perhaps you should add the directory containing `glib-2.0.pc'
>   to the PKG_CONFIG_PATH environment variable
>   No package 'glib-2.0' found

**Comment by knopp** [comment]
You need to have libglib2.0-dev installed.
```
sudo apt-get install -y libglib2.0-dev
```

**Comment by knopp** [comment]
Actually, it should probably be a dependency of `libgtk-3-dev`. So you will need to install that.

**Comment by iamgabrielsoft** [comment]
yeah installing libgtk-3-dev and libglib2.0-dev solved the problem
