### ISSUE TITLE
Add support for platform plugins

### ISSUE THREAD

**Issue by knopp** [nativeshell/nativeshell#6]
This issue tracks progress for platform plugins support.

NativeShell support Flutter packages, but it does not yet support packages that contain native code (plugins). 

- [ ] Support of macOS platform plugins
- [ ] Support of Windows platform plugins
- [ ] Support of Linux platform plugins

**Comment by wilsonowilson** [comment]
Woah that was fast! Thanks for addressing this so quickly!
