### ISSUE TITLE
Add Minimize, Maximize, MaximizeOrRestore functions support

### ISSUE THREAD

**Issue by prateekmedia** [nativeshell/nativeshell#60]
As CSD support is complete by setting frame to WindowFrame.noTitle, the only thing missing is the titlebar button functions support.

**Comment by prateekmedia** [comment]
This can be done by GTK on linux, UWP on windows and AppKit on macos.

**Comment by knopp** [comment]
Can you be more specific? By default (when not customizing title bar) GTK is using CSD on gnome and SSD on KDE. What better support exactly do you have in mind?

**Comment by prateekmedia** [comment]
- Let us create a native looking header for desktop platforms
- which also follow CDs standards like rounded corner and drop shadows like a native desktop app.
- Follow themingfor header like gtk theming and window buttons for linux or windows theming for light/dark mode , or macos inline title bar look 

Ultimately I want to achieve this using nativeshell:

![](https://i.stack.imgur.com/knQ7T.png)

**Comment by knopp** [comment]
If you set window frame to WindowFrame.noTitle, it should still have shadow and possibly rounded corners.

**Comment by prateekmedia** [comment]
> If you set window frame to WindowFrame.noTitle, it should still have shadow and possibly rounded corners.

Ok I will try it, also can we mimic current theming headerbar for platforms like gtk to lookmmore native, It is possible in GTK but I don't know much about it.

**Comment by knopp** [comment]
You can make custom title bar (or any draggable section) by calling `Window.of(context).beginDrag()` from a gesture detector. There's currently no support for maximizing/minimizing window and listening to window states, but that will come soon. That should be enough to build any custom title bar.

**Comment by prateekmedia** [comment]
@knopp And please if possible make max, min, close icon native to the current Operating system and theming.

**Comment by knopp** [comment]
That is not really possible, nor goal of flutter / nativeshell. If you want to do that, then you can just write native code and customize the GtkHeaderBar of the window. If you're making a custom window you're in charge of anything you put in there.

**Comment by prateekmedia** [comment]
> WindowFrame.noTitle

Can you guide me how or where to set that, I cannot find a way to set this for the parent/main window

**Comment by prateekmedia** [comment]
@knopp Is there any way to get response from window manager to check if titlebar buttons are to be shown or not?

Use case:
on mobile linux with custom titlebar buttons, the visiblity of maximize, minimize and close button is not neccesary as it will always be controlled by window manager.

But because this was custom implementation inside flutter code so titlebar buttons will still be visible.

I want to get a callback from shell something like `Window.of(context).isTitlebarButtonVisible`.

This can also be used for windows phone and apps, I don't know about mac as it only have a desktop ui so this method will always return true on that.

For ios / android this method will return false as titlebar is not needed there.

**Comment by knopp** [comment]
You can not use nativeshell with iOS / Android. It is desktop only at this point.

**Comment by prateekmedia** [comment]
@knopp Yeah, I only gave an example if the callback is added to this plugin.

**Comment by prateekmedia** [comment]
679926156ed569e598f231f7ebe6db39376edd20 has this implemented but it is not auto and you need to provide the maximize minimize value.

Like
`setMaximize(true)`

But I wanted an auto method which would restore if maximized and maximize if restore like
`maximizeOrRestore`

@knopp Can this be implemented?

**Comment by knopp** [comment]
Something like this should work:
```dart
    final flags = await window.getWindowStateFlags();
    await window.setMaximized(!flags.maximized);
```

**Comment by prateekmedia** [comment]
@knopp Can this be a method so that it would be easy and I will not have to repeat the code.

**Comment by knopp** [comment]
You can easily make it an extension method.

**Comment by prateekmedia** [comment]
Thanks, I will close this then.
