### ISSUE TITLE
How to set WindowFrame.noTitle property for a window

### ISSUE THREAD

**Issue by prateekmedia** [nativeshell/nativeshell#65]
> WindowFrame.noTitle

Can you guide me how or where to set that, I cannot find a way to set this for the parent/main window

_Originally posted by @prateekmedia in https://github.com/nativeshell/nativeshell/issues/60#issuecomment-901451413_

This is a question and not an issue, but because discussions tab is not enabled, I am posting it here.

**Comment by knopp** [comment]
Inside your `WindowState` subclass override `initializeWindow` 
```dart
  Future<void> initializeWindow(Size contentSize) async {
    ...
    await window.setStyle(WindowStyle(
      ...
      frame: WindowFrame.noTitle,
    ));
    ...
  }
```

**Comment by prateekmedia** [comment]
Thanks @knopp, I will try it out!
