### ISSUE TITLE
Create a community space

### ISSUE THREAD

**Issue by Janrupf** [nativeshell/nativeshell#66]
NOTE: This is a meta issue, and not related to technical functionality.

It would be nice to have a community space for chatting and resolving issues. I'm quite interested in the project, but at the moment its hard to reach out in an interactive chat. Questions in general often don't belong into github issues and are better answered in an interactive conversation.

My suggestion would be to use the issue tracker on Github as a bug tracker and have a separate chat instance (possibly a discord) as a community space for showcasing and discussion. If the project gains more attention, this would become a huge benefit opposed to just having issues.

Thanks for the project, lets give it a proper community space!

**Comment by prateekmedia** [comment]
Or to use Github discussions?

**Comment by knopp** [comment]
Discord does seem like a good idea.

**Comment by Janrupf** [comment]
@knopp little resurrection of the issue, I still think this is needed. 

I wanted to contact you on discord about this and just ask you there, but on your Github profile you didn't include the tag for Discord (only the user name), so I can't actually message you.
