### ISSUE TITLE
Configuring Mac files

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#67]
I'd like to know how we can tinker with macOS configuration files like the `Podfile` or `Release.entitlements`. Is there any way to edit files like these?

**Comment by knopp** [comment]
The Podfile is internally generated during build from flutter plugins. You can add `macos_extra_pods` argument to `FlutterOptions` inside `build.rs` if you want to add additional pods to the build, i.e.

```rust
    Flutter::build(FlutterOptions {
        macos_extra_pods: &[
            "pod 'Sparkle'", //
            "pod 'LetsMove'",
        ],
        ..Default::default()
    })?;
```

There is no code-signing during cargo build, so there is no entitlements file. There is [bundle_tool](https://github.com/nativeshell/bundle_tool) project that you can install using

```
cargo install bundle_tool
```

and which can create self contained bundle as well as codesign them, but I haven't had much time to document it. After installing you can run  `cargo bundle-tool --help` and see the available options.

**Comment by wilsonowilson** [comment]
I see. On a side note would be really helpful if there was documentation highlighting the process of building and releasing Desktop apps with Nativeshell.
