### ISSUE TITLE
Native shell debugger just like flutter for Vscode / android studio

### ISSUE THREAD

**Issue by prateekmedia** [nativeshell/nativeshell#68]
Currently we have to run the app manually using `cargo run`, It would be interesting to see if there will be a debugger for this.

This will make this package developer friendly and also in future when you add hot restart or reload, then we don't have to use the terminal instead use the debugger in our IDE(vscode is more general then android-studio for desktop).

**Comment by knopp** [comment]
There is a launcher configuration for vscode that you can use to attach to running process to get debugging and hot reload functionality. There's no such thing for android studio unfortunately because the intellij flutter plugin doesn't support attach to desktop.

**Comment by prateekmedia** [comment]
> There is a launcher configuration for vscode

Any links or additional information will be appreciated.

**Comment by knopp** [comment]
See this file: https://github.com/nativeshell/app_template/blob/main/.vscode/launch.json

After you launch app with cargo run, you can launch the `Flutter: Attach to Process` configuration from VSCode and it should attach to running process.

**Comment by thenextman** [comment]
Note that this wouldn't work for me if my nativeshell project was not the root folder in VSCode. It would always fail to connect to the VM service.

I resolved that by creating a VS Code workspace; this allowed creating the .vscode/launch.json inside the nativeshell project folder instead of at the root directory.
