### ISSUE TITLE
Window Resize area too large on linux

### ISSUE THREAD

**Issue by prateekmedia** [nativeshell/nativeshell#70]
OS: Elementary os odin

As you can see my cursor[bottom-center] I can resize window from 2-3 cm away too, which is not the case for normal windows.

![nativeshell-windowresizebug](https://user-images.githubusercontent.com/41370460/130368167-31e0657d-6fad-45dc-83e2-d9889f2a5fac.png)

**Comment by knopp** [comment]
Is that a NativeShell application?

**Comment by prateekmedia** [comment]
@knopp yes, with frame set to `WindowFrame.noTitle` (well it doesn't depend on frame) and [`gtk-flutter`](https://github.com/prateekmedia/gtk-flutter) package.

**Comment by knopp** [comment]
I can't reproduce this on Windows/WSL and I don't have access to my linux machine right now. I'll try to look into this next week.

**Comment by prateekmedia** [comment]
@knopp  I tried it on pop os and it didn't happened there, looks like it only happened on elementary os. So I think this can be closed.
