### ISSUE TITLE
Distribute binaries easily

### ISSUE THREAD

**Issue by prateekmedia** [nativeshell/nativeshell#71]
I know this is in the roadmap of nativeshell, but still currently if I run `cargo build --release` then it works but when I try to open the executable then it result in the error:
```
./target/release/appimagepool: error while loading shared libraries: liburl_launcher_linux_plugin.so: cannot open shared object file: No such file or directory
```
and doesn't launches. Same goes if I run debug mode executable from `/target/debug/appimagepool`.
On the other hand `cargo run` works fine.

Is there any way to fix this behavior, I can just pack it to appimage by myself afterwards.

**Comment by knopp** [comment]
Does your `.cargo/config.toml` look like [this](https://github.com/nativeshell/app_template/blob/main/.cargo/config.toml)?

**Comment by prateekmedia** [comment]
Oh looks like I forgot to add that file, thanks @knopp for your help, things plugin is truly great.
