### ISSUE TITLE
Customising the title bar on macOS

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#74]
Related to #67.

<img width="846" alt="Screenshot 2021-08-28 at 17 05 53" src="https://user-images.githubusercontent.com/63465656/131223953-8173ee43-7ddd-4953-a3f3-5918d21650f5.png">

Making the title bar transparent can usually be achieved by editing the `MainMenu.xib` file. 

How can I achieve this with nativeshell?

**Comment by knopp** [comment]
The NativeShell approach would be to put this in `initializeWindow`:

```dart
    await window.setStyle(WindowStyle(
      frame: WindowFrame.noTitle,
      trafficLightOffset: const Offset(16, 18), // move the standard window buttons
    ));
```

This should give you window without the title bar. After that, for any area where you want your window to be draggable, use `GestureDetector` and on `panStart` call `Window.of(context).performDrag();`. 

This should work across all platforms (except of `trafficLightOffset` which is ignored on linux and windows).

**Comment by wilsonowilson** [comment]
Awesome! Thanks!
