### ISSUE TITLE
Working with the MacOS "Emoji & Symbols" popup

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#75]
Clicking the fn (globe) key or selecting the "Emoji & Symbols" menu under the edit menu on macOS opens up the emojis and symbols popup.

At the moment, adding symbols works with `EditableText` in Flutter. However, the popup is not positioned next to the caret and doesn't leave the screen even after clicking a symbol. (I also can't pinpoint what is responsible for accepting a symbol from the popup).

Is there any way to manually provide an anchor to the popup and retrieve the selected symbol using NativeShell?

https://user-images.githubusercontent.com/63465656/131248139-403acd8c-1616-4c5e-a4eb-5f2d2e92ec58.mov

**Comment by knopp** [comment]
This is something that would need to be fixed in flutter engine.
