### ISSUE TITLE
it's allowed sub window use same object from main window ?

### ISSUE THREAD

**Issue by imiskolee** [nativeshell/nativeshell#81]
hi:
I think sub window also running on same process space, so can we directly sharing object between 2 sub windows.

**Comment by knopp** [comment]
It is running in same process, but each window is a separate dart isolate. You can't share dart objects between isolates (there's work currently being done on light-weight isolates that would make sending objects between isolates cheaper, but that's not yet supported on desktop embedders and still doesn't let you share single object between isolates).

**Comment by imiskolee** [comment]
got it. thanks!
