### ISSUE TITLE
how can we use this framework without cargo?

### ISSUE THREAD

**Issue by imiskolee** [nativeshell/nativeshell#84]
Hi:

how can we use this framework as a normal pub? without any rust related things(cargo, rust sources)

if used cargo run to launch app,  looks like the IDEA Flutter plugin can not works.

**Comment by knopp** [comment]
I'm not sure what you mean. Without rust nativeshell is just a thin abstraction over some platform channels that have no implementation (that's the rust part). Sadly intellij idea doesn't support attaching to running desktop project and thus vscode is recommended.
