### ISSUE TITLE
`WindowFrame.noTitle` doesn't remove title from title bar

### ISSUE THREAD

**Issue by wilsonowilson** [nativeshell/nativeshell#89]
Setting the window style to `WindowFrame.noTitle` should remove the title and the title bar. But after setting the title of the window with `Window.setTitle`, the title still appears on the window.

<img width="1151" alt="Screenshot 2021-09-07 at 15 54 10" src="https://user-images.githubusercontent.com/63465656/132366732-b85f49e3-56af-460b-a791-1a6b0f36c64d.png">

As far as I know, the title of the window is necessary for window management in the application.

<img width="1033" alt="Screenshot 2021-09-07 at 16 06 06" src="https://user-images.githubusercontent.com/63465656/132368013-007e0d24-0858-4d6d-bd5b-3dcc7152e84f.png">

Because of this, it would be great if there was a way to remove the title from the title bar, but make sure the window remains named.

**Comment by knopp** [comment]
Agreed, the title should not be displayed in this case. This is a bug.
