### ISSUE TITLE
Requires "Developer mode" to be enabled on Windows for symlinks to work

### ISSUE THREAD

**Issue by timfish** [nativeshell/nativeshell#9]
This is looking great! 

I decided to try out building and running the example on Windows too and hit an issue where permission was denied creating a symlink to `flutter_export.h` in the build process. 

It turns out you can't create symlinks on Windows without elevated permissions unless you've enabled "Developer mode". It might  be worth capturing this panic on Windows and pointing them at the official docs:
https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development

**Comment by knopp** [comment]
It turns out that even if I disable developer mode, I can still make symlinks. So it seems that perhaps once enabled it is enabled forever :-/
