### ISSUE TITLE
Unable to integrate into workspace

### ISSUE THREAD

**Issue by thenextman** [nativeshell/nativeshell#90]
I doubt this is a NativeShell issue specifically; but I'm struggling to understand the problem and hope you might have some insight. As an aside - have you considered setting up a Discord (or similar) server for project discussion?

I cloned the app_template and added it to my cargo workspace, so it's built alongside our main project crate. However - it no longer compiles:

```
[workspace]
members = [
    "frontend", # NativeShell app_template
    "libcompany/rust", # Existing business logic
]
default-members = [
    "frontend",
    "libcompany/rust",
]
```

`cargo build`

> error[E0277]: `*const Class` cannot be sent between threads safely
   --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/nativeshell-0.1.9/src/shell/platform/macos/app_delegate.rs:156:1
    |
156 | / lazy_static! {
157 | |     static ref APPLICATION_DELEGATE_CLASS: ApplicationDelegateClass = unsafe {
158 | |         let superclass = class!(NSObject);
159 | |         let mut decl = ClassDecl::new("IMApplicationDeleagte", superclass).unwrap();
...   |
247 | |     };
248 | | }
    | |_^ `*const Class` cannot be sent between threads safely
    |
    = help: within `ApplicationDelegateClass`, the trait `Send` is not implemented for `*const Class`
note: required because it appears within the type `ApplicationDelegateClass`
   --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/nativeshell-0.1.9/src/shell/platform/macos/app_delegate.rs:153:8
    |
153 | struct ApplicationDelegateClass(*const Class);
    |        ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: required because of the requirements on the impl of `Sync` for `spin::once::Once<ApplicationDelegateClass>`
    = note: required because it appears within the type `lazy_static::lazy::Lazy<ApplicationDelegateClass>`
    = note: shared static variables must have a type that implements `Sync`
    = note: this error originates in the macro `__lazy_static_create` (in Nightly builds, run with -Z macro-backtrace for more info)

And the same for `MenuItemTargetClass`, `WindowClass` and `WindowDelegateClass`

What I've tried:

- Deleting the workspace level Cargo.lock
- Checking that the versions of `lazy_static` is consistent between nativeshell and my project crate (it is - 1.4.0)

I wondered if that might be an issue with the objc crate; but I see something similar on Windows:

>error[E0277]: `std::rc::Weak<WindowClass>` cannot be sent between threads safely
  --> C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\nativeshell-0.1.9\src\shell\platform\win32\window_adapter.rs:14:1
   |
14 | / lazy_static! {
15 | |     static ref GLOBAL: Global = Global {
16 | |         window_class: RefCell::new(Weak::new()),
17 | |     };
18 | | }
   | |_^ `std::rc::Weak<WindowClass>` cannot be sent between threads safely
   |
   = help: the trait `Send` is not implemented for `std::rc::Weak<WindowClass>`
   = note: required because of the requirements on the impl of `Send` for `RefCell<std::rc::Weak<WindowClass>>`
note: required because it appears within the type `window_adapter::Global`
  --> C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\nativeshell-0.1.9\src\shell\platform\win32\window_adapter.rs:8:8
   |
8  | struct Global {
   |        ^^^^^^
   = note: required because of the requirements on the impl of `Sync` for `spin::once::Once<window_adapter::Global>`
   = note: required because it appears within the type `lazy_static::lazy::Lazy<window_adapter::Global>`
   = note: shared static variables must have a type that implements `Sync`
   = note: this error originates in the macro `__lazy_static_create` (in Nightly builds, run with -Z macro-backtrace for more info)

I *do* understand what the error is telling me, but struggling to see how I end up in this position.

**Comment by thenextman** [comment]
Alright, I tracked this down to a weird conflict with a specific dependency in our existing crate. I'll chat to the developer on that and see what I can figure out.

**Comment by knopp** [comment]
Perhaps there is an older version of lazy_static that requires types to be `Send` as well? In NativeShell we know that the static is only used from main thread so if this is a big problem maybe we could just add `unsafe impl Send for Global {}`, but it would be good to know why exactly is this happening.

**Comment by thenextman** [comment]
@knopp I got to the bottom of this, but I don't know the appropriate fix

lazy_static is pulled in a few places, always 1.4.0. However, one of our dependencies pulls in [rsa](https://github.com/RustCrypto/RSA) and [num-bigint](https://github.com/dignifiedquire/num-bigint); both of which enable the `spin_no_std` feature of lazy_static. Once one dependency enables a feature, everybody gets it.

I can't find the documentation on it, but it's that feature that's requiring `Send` across the board.

I can fix this by adding `unsafe impl Send...` (at least on macOS, that's for `ApplicationDelegateClass`, `MenuItemTargetClass`, `WindowClass` and `WindowDelegateClass`. On Windows it's `Global`. I didn't check Linux yet. I could make a PR to that effect.

Otherwise, we could just build our own fork of nativeshell and wait until this all gets worked out upstream. In general there seems [some concern](https://github.com/rust-lang-nursery/lazy-static.rs/issues/150) over that feature of lazy_static.

Do you have another idea?

**Comment by knopp** [comment]
I took a look at the `spin-rs` crate and it seems to be that it is using a very basic spin lock under the hood that might suffer from priority inversion. I find it quite concerning that there are crates unconditionally forcing this behavior.

[This](https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html) might be relevant.

All this aside, I do not mind adding `Send` to these classes knowing now that `lazy_static` might be requiring this in some circumstances. If you submit the PR (preferably with a comment explaining why it there is `unsafe Send`) I can merge it.

**Comment by thenextman** [comment]
@knopp I will go ahead and do that within the next day or two. Thanks again!

**Comment by thenextman** [comment]
I raised PR#91 to correct this.

A further incompatibility arrises with workspaces: when building from the workspace, the project-level `.cargo/config.toml` is not consulted. Since (at least on macOS) the rpath is not properly set, the final binary fails with a dynamic linker error.

Currently we can workaround by specifying the configuration inside build.rs instead:

e.g. `println!("cargo:rustc-link-arg=-Wl,-rpath,@executable_path");`

That's an unstable feature until rust 1.56, so we also to use nightly and a modified build command:

e.g. `cargo +nightly build -p nativeshell -Zextra-link-arg`

**Comment by knopp** [comment]
I planned to add rpath to `rustc-link-arg` as soon as 1.56 becomes stable. I'll be very happy to get rid of `.cargo/config.toml`.
